#!/bin/bash
# Build the Rust face tracking daemon, then assemble the
# viewos-face-daemon package.
#
# Requires a Rust toolchain and system OpenCV development files. The opencv
# crate can build OpenCV from source, which takes the best part of an hour and
# needs a lot of disk; linking the distribution's copy instead is both much
# faster and much more likely to match the runtime libraries users actually
# have. The OPENCV_* variables below are what select that path.
set -euo pipefail
# shellcheck source=lib/build-common.sh
source "$(dirname "$(readlink -f "$0")")/lib/build-common.sh"

require cargo dpkg-deb

DAEMON_SRC_DIR="${REPO_ROOT}/face-tilt/daemon"
PKG_SRC_DIR="${PACKAGE_SRC_DIR}/viewos-face-daemon"

# --- System OpenCV -------------------------------------------------------
#
# opencv-sys builds a vendored OpenCV unless it is told otherwise. We point it
# at the distribution's, listing the libraries explicitly because the
# auto-discovery order varies between build environments and picking a
# different one is a common cause of "works on my machine".
OPENCV_INCLUDE_PATHS="${OPENCV_INCLUDE_PATHS:+/usr/include/opencv4}"
OPENCV_LINK_PATHS="${OPENCV_LINK_PATHS:+/usr/lib/x86_64-linux-gnu}"
OPENCV_LINK_LIBS="${OPENCV_LINK_LIBS:+,opencv_core,opencv_imgproc,opencv_imgcodecs,opencv_dnn,opencv_videoio,opencv_video,opencv_calib3d,opencv_features2d,opencv_flann}"
export OPENCV_INCLUDE_PATHS OPENCV_LINK_PATHS OPENCV_LINK_LIBS

# The crate's build script shells out to cmake to probe the OpenCV it finds.
command -v cmake >/dev/null 2>&1 || die "cmake is required to probe the system OpenCV"
command -v pkg-config >/dev/null 2>&1 || die "pkg-config is required to probe the system OpenCV"

if ! pkg-config --exists opencv4; then
    die "opencv4 not found by pkg-config. On Debian install libopencv-dev."
fi
info "using system OpenCV $(pkg-config --modversion opencv4)"

# --- Build ---------------------------------------------------------------
info "building viewos-face-daemon"
# The build directory lives outside the source tree so a stray target/ is not
# picked up by the packaging step below.
#
# Not built with --locked: Cargo.lock is generated by the first successful
# build and committed, at which point --locked should be added here so the
# dependency versions cannot drift between builds of the same source.
CARGO_TARGET_DIR="${DAEMON_SRC_DIR}/target" cargo build \
    --manifest-path "${DAEMON_SRC_DIR}/Cargo.toml" \
    --release

binary="${CARGO_TARGET_DIR}/release/viewos-face-daemon"
[ -x "$binary" ] || die "cargo did not produce ${binary}"

# --- Package -------------------------------------------------------------
info "populating ${PKG_SRC_DIR}"
rm -rf "${PKG_SRC_DIR}/usr/bin"
install -d "${PKG_SRC_DIR}/usr/bin"
install -m 0755 "$binary" "${PKG_SRC_DIR}/usr/bin/viewos-face-daemon"

# The YuNet model is not committed, so it is fetched and hash-checked here
# rather than assumed present. Failing the build is the point: a package with
# no model installs cleanly and then detects nothing.
info "ensuring the YuNet model is present"
"${REPO_ROOT}/packages/fetch-yunet-model.sh"

deb="$(build_package "$PKG_SRC_DIR")"
lint_package "$deb"

info "removing the cargo build directory"
rm -rf "${DAEMON_SRC_DIR}/target"
